name: Deploy Viewer to GitHub Pages

on:
  push:
    branches:
      - embedding-release


jobs:
  build-embedding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Build Embedding ğŸ› 
        run: |
          cd frontend
          pnpm install
          pnpm run build:embed
      - name: Pubish Release ğŸ“¦
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            frontend/dist/embed.es.js
            frontend/dist/embed.umd.js
