name: Test release

on:
  push:
    branches:
      - embedding-release


jobs:
  build-embedding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Bump version and push tag ğŸ·
        id: tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Install pnpm âš™
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Install treemaps library ğŸ“¦
        run: |
          cd frontend
          git clone --branch hiviser_deployment https://${{ secrets.SEERENE_TREEMAPS_DEPLOY_USER }}:${{ secrets.SEERENE_TREEMAPS_DEPLOY_TOKEN }}@gitlab.hpi3d.de/seerene/treemaps.git
          cd treemaps
          npm install
          npm run build-lib

      - name: Build Embedding ğŸ› 
        run: |
          cd frontend
          pnpm install
          pnpm run build:embed

      - name: Pubish Release ğŸš€
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          draft: true
          tag_name: ${{ steps.tag.outputs.new_tag }}
          files: |
            frontend/dist/embed.es.js
            frontend/dist/embed.umd.js
